// <auto-generated />
namespace self01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewNavigationInLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewNavigationInLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201406060356205_NewNavigationInLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
